exclude: "templates/configuration.template.tfvars"
repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.77.1"
  hooks:
    - id: terraform_fmt
      args:
        - --args=-recursive
        - --args=-diff
- repo: https://github.com/terraform-docs/terraform-docs
  rev: "v0.16.0"
  hooks:
    - id: terraform-docs-go
      args: ["--config", ".terraform-docs.yml", "."]
