formatter: "markdown table"

output:
  file: README.md
  mode: replace

header-from: header.md

content: |-
  {{ .Header }}
  {{ .Providers }}
  {{ .Requirements }}
  {{ .Resources }}
  {{ .Modules }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Footer }}

sections:
  hide:
    - modules
    - providers
    - requirements

settings:
  anchor: false
  color: true
  default: true
  description: true
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
